### ISSUE TITLE
cannot convert voc to tfrecords

### ISSUE THREAD

**Issue by Amanpradhan** [vijendra1125/Tensorflow_Object_detection_API-Custom_Faster_RCNN#1]
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /media/aman/48aca5a1-5813-4608-90a1-8660bc24c17e/Tensorflow_Object_detection_API-Custom_Faster_RCNN/dataset/VOC2007/ImageSets/Main/aeroplane_train.txt; No such file or directory

**Comment by vijendraxsingh** [comment]
are you using create_tf_trecord.py given in extra folder of this repo?
I think you are not using the modified script but the default one given by Tensorflow.

**Comment by justshot** [comment]
I got the same problem

**Comment by justshot** [comment]
Problem solved by using extra python.

**Comment by vijendraxsingh** [comment]
@justshot can you please explain what do you mean by extra python?

**Comment by justshot** [comment]
using create_tf_trecord.py given in extra folder of this repo.  Thank you!

**Comment by vijendraxsingh** [comment]
Thank you for clarifying the comment.

**Comment by justshot** [comment]
Thank you for sharing this project!
